// ---------- Amano data ----------

const NEIGHBORHOODS = [
  {
    id: "cap-cana",
    name: "Cap Cana",
    short: "Exclusive marina & villas",
    blurb: "A sanctuary of exclusivity with private beaches, a world-class marina, and luxury villas that command premium rates year-round.",
    // isometric tile position (col, row) on a 10x7 grid of Punta Cana region
    tile: { x: 8, y: 5 },
    color: "#C5623A",
    avgNightly: 640,
    occupancy: 82,
    demand: "High",
    demandScore: 92,
    properties: 3,
    highlights: ["Marina", "Private beach", "Golf"],
  },
  {
    id: "punta-cana-village",
    name: "Punta Cana Village",
    short: "Airport-adjacent, family hub",
    blurb: "A vibrant hub near the airport with strong community appeal for families and business travelers.",
    tile: { x: 7, y: 4 },
    color: "#D07B45",
    avgNightly: 310,
    occupancy: 76,
    demand: "Steady",
    demandScore: 74,
    properties: 2,
    highlights: ["Airport 7 min", "Walkable", "Family-friendly"],
  },
  {
    id: "vista-cana",
    name: "Vista Cana",
    short: "Modern fast-rising community",
    blurb: "A modern, fast-rising community with lakes, golf, and smart developments attracting investors.",
    tile: { x: 6, y: 5 },
    color: "#2E7A7A",
    avgNightly: 245,
    occupancy: 79,
    demand: "Rising",
    demandScore: 81,
    properties: 4,
    highlights: ["New builds", "Lake & golf", "Investor favorite"],
  },
  {
    id: "los-corales",
    name: "Los Corales",
    short: "Walkable beachfront",
    blurb: "A lively beachfront enclave known for walkability, beach access, and consistent rental demand.",
    tile: { x: 7, y: 3 },
    color: "#A84E2A",
    avgNightly: 285,
    occupancy: 88,
    demand: "High",
    demandScore: 90,
    properties: 2,
    highlights: ["Beach 2 min", "Restaurants", "Walkable"],
  },
  {
    id: "el-cortecito",
    name: "El Cortecito",
    short: "Tourist heart of Bavaro",
    blurb: "A popular tourist area of Bavaro featuring beachfront condos, diverse restaurants, and local shops.",
    tile: { x: 6, y: 3 },
    color: "#3A8F82",
    avgNightly: 220,
    occupancy: 84,
    demand: "Steady",
    demandScore: 78,
    properties: 1,
    highlights: ["Beachfront condos", "Dining", "Local life"],
  },
  {
    id: "el-cocotal",
    name: "El Cocotal",
    short: "Tranquil gated golf community",
    blurb: "A tranquil gated golf community offering stable income opportunities in a residential setting.",
    tile: { x: 5, y: 4 },
    color: "#1F5A5A",
    avgNightly: 260,
    occupancy: 71,
    demand: "Stable",
    demandScore: 68,
    properties: 1,
    highlights: ["Gated", "Golf course", "Residential"],
  },
  {
    id: "santo-domingo",
    name: "Santo Domingo",
    short: "Colonial capital",
    blurb: "The Dominican capital — historic Zona Colonial, waterfront Malecón, and business-class demand.",
    tile: { x: 1, y: 4 },
    color: "#4E6E8C",
    avgNightly: 180,
    occupancy: 72,
    demand: "Steady",
    demandScore: 70,
    properties: 1,
    highlights: ["Zona Colonial", "Business stays", "Year-round"],
    region: "other",
  },
  {
    id: "cabrera",
    name: "Cabrera",
    short: "North coast · raw nature",
    blurb: "A wild, oceanview stretch of the north coast — cliffs, untouched beaches, and eco-villas built for retreats and multi-generational stays. Minutes to Playa Grande and Amanera.",
    tile: { x: 3, y: 1 },
    color: "#356A8F",
    avgNightly: 1200,
    occupancy: 64,
    demand: "Event-driven",
    demandScore: 76,
    properties: 1,
    highlights: ["Oceanview", "Retreats & weddings", "Eco escape"],
    region: "other",
  },
];

// four listings (we have airbnb links, but can't scrape — use plausible titles tied to areas)
const PROPERTIES = [
  {
    id: "p1",
    title: "Coral Pavilion",
    area: "Cap Cana",
    neighborhoodId: "cap-cana",
    beds: 4, baths: 3, guests: 8,
    nightly: 685,
    rating: 4.97,
    reviews: 128,
    link: "https://www.airbnb.com/rooms/1645837239289257011",
    desc: "Four-bed villa inside Cap Cana's gated marina community. Private plunge pool, chef's kitchen, and a 90-second golf-cart ride to Juanillo Beach.",
    img: "./images/prop-1.jpg",
    features: ["Private pool", "Ocean view", "Superhost"],
  },
  {
    id: "p2",
    title: "Casa Aqua Dip",
    subtitle: "Walk-to-dining duplex",
    area: "Punta Cana Village",
    neighborhoodId: "punta-cana-village",
    beds: 3, baths: 2.5, guests: 7,
    nightly: 325,
    rating: 4.88,
    reviews: 8,
    link: "https://www.airbnb.com/rooms/1597879829057642475",
    desc: "Private duplex villa in Punta Cana Village's no-car-needed zone inside Punta Cana Resort & Club. Oversized private pool, walk to restaurants and cafés, 3 minutes to PUJ, beach club access.",
    img: "./images/aqua-exterior.avif",
    gallery: [
      "./images/aqua-exterior.avif",
      "./images/aqua-pool.avif",
      "./images/aqua-living.avif",
      "./images/aqua-kitchen.avif",
    ],
    features: ["Private pool", "Airport 3 min", "Walk to dining", "Guest Favorite"],
  },
  {
    id: "p3",
    title: "Sunset House",
    subtitle: "Rare 4BR golf villa",
    area: "Vista Cana",
    neighborhoodId: "vista-cana",
    beds: 4, baths: 3.5, guests: 8,
    nightly: 250,
    rating: 4.95,
    reviews: 63,
    link: "https://www.airbnb.com/rooms/1600052755196125616",
    desc: "Private 4BR luxury villa in gated Oasis Vista Cana. Oversized pool overlooking the golf course, jacuzzi, and walkable to bars, dining, and night golf. 15 min to PUJ, 25 min to Cap Cana.",
    img: "./images/sunset-exterior.avif",
    gallery: [
      "./images/sunset-pool.avif",
      "./images/sunset-terrace.avif",
      "./images/sunset-dining.avif",
      "./images/sunset-bedroom.avif",
      "./images/sunset-exterior.avif",
    ],
    features: ["Private pool + jacuzzi", "Gated · 24/7 security", "Walk to golf", "Superhost"],
  },
  {
    id: "p4",
    title: "Colonial Loft",
    area: "Santo Domingo",
    neighborhoodId: "santo-domingo",
    beds: 1, baths: 1, guests: 2,
    nightly: 175,
    rating: 4.91,
    reviews: 47,
    link: "https://www.airbnb.com/rooms/1549353242023471473",
    desc: "A quiet loft steps from the Zona Colonial. Exposed beams, rooftop terrace, and five minutes to the Malecón. Ideal for business travelers.",
    img: "./images/prop-4.jpg",
    features: ["Zona Colonial", "Rooftop", "Walk everywhere"],
  },
  {
    id: "p5",
    title: "Oceanview Luxe",
    subtitle: "Eco villa for 26 · 14 king beds",
    area: "Cabrera",
    neighborhoodId: "cabrera",
    beds: 8, baths: 8.5, guests: 26,
    nightly: 1200,
    rating: 5.00,
    reviews: 6,
    link: "https://www.airbnb.com/",
    desc: "Private oceanview villa built for retreats, weddings, and large celebrations up to 26 guests. Infinity saltwater pool, two full kitchens, 8 bedrooms across two wings, wrapped in raw Caribbean nature. Minutes to Playa Grande and Amanera.",
    img: "./images/ocean-sunset.avif",
    gallery: [
      "./images/ocean-sunset.avif",
      "./images/ocean-pool.avif",
      "./images/ocean-terrace.avif",
      "./images/ocean-kitchen.avif",
      "./images/ocean-bath.avif",
    ],
    features: ["Sleeps 26", "Infinity saltwater pool", "Oceanview", "Guest Favorite"],
  },
];

const SERVICES = [
  { k: "01", title: "Guest Reservations & Communication",
    body: "Automated booking with AI-assisted messaging delivers quick, accurate, and friendly replies — a seamless experience from inquiry to checkout." },
  { k: "02", title: "Housekeeping & Maintenance",
    body: "Smart scheduling optimizes cleaning and maintenance. Real-time updates keep your property consistently guest-ready, never over-booked or under-prepped." },
  { k: "03", title: "Dynamic Pricing Optimization",
    body: "AI-powered pricing tracks demand, seasonality, and local market trends to set a transparent nightly rate that maximizes revenue without leaving gaps." },
  { k: "04", title: "Guest Support, 24/7",
    body: "Integrated communication with automated alerts means faster response to guest needs, backed by a dedicated human team for the moments that matter." },
  { k: "05", title: "Financial Transparency & Reporting",
    body: "Owners are paid directly by the platform and enjoy live access to booking and performance data. No monthly statements, no surprises, just clarity." },
];

const TESTIMONIALS = [
  { quote: "My occupancy jumped from 58% to 84% in three months. Amano's pricing engine is doing work I couldn't do manually.",
    name: "Marcela D.", role: "Owner · 2 villas, Cap Cana" },
  { quote: "Every guest leaves a five-star review. The housekeeping team is invisible and that's the point.",
    name: "Tomás R.", role: "Owner · Vista Cana" },
  { quote: "Having live dashboards instead of end-of-month statements completely changed how I think about my investment.",
    name: "Priya K.", role: "Investor · Los Corales" },
];

const STATS = [
  { k: "4.94★", v: "average rating" },
  { k: "8+",   v: "years hosting" },
  { k: "300+", v: "stays hosted" },
  { k: "90%",  v: "response rate" },
];

const FOUNDERS = [
  { name: "Joe Santos",       role: "Co-founder · Operations" },
  { name: "Benjamin Rosario", role: "Co-founder · Technology" },
  { name: "César Suriel",     role: "Co-founder · Hospitality" },
];

const CONCIERGE = [
  { k: "A", title: "Private chef",
    body: "In-villa breakfasts, candlelit dinners, Dominican tasting menus — our chefs plan, shop, cook, and clean up so your kitchen stays yours.",
    tag: "From $180 / service" },
  { k: "B", title: "Airport & island transfers",
    body: "Private SUV pickup from PUJ with a named driver, cold towels, and bottled water. On-call transport anywhere on the coast, day or night.",
    tag: "From $65 one-way" },
  { k: "C", title: "In-villa spa & massage",
    body: "Licensed therapists bring the table, oils, and ocean soundtrack to your terrace. Couples massages, deep tissue, or post-flight recovery.",
    tag: "From $120 / 60 min" },
];

Object.assign(window, { NEIGHBORHOODS, PROPERTIES, SERVICES, CONCIERGE, TESTIMONIALS, STATS, FOUNDERS });
